### ISSUE TITLE
Scoop 1.2.0 fails out of the box due to missing nett.dll

### ISSUE THREAD

**Issue by asmundg** [fsharp-editing/Forge#12]
Trying to run forge --help from the unpacked 1.2.0 release zip results in the following exception. Seems like there's a dependency missing from the bundle (or a missing step about dependencies in the installation instructions).

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Nett, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at Forge.Alias.parse(String path)
   at Forge.Alias.load()
   at Forge.Commands.applyAlias(String[] args)
   at Forge.Commands.strikeForge(String[] args, Result cont)
   at Forge.App.main(String[] argv)
```

**Comment by asmundg** [comment]
That was an interesting slip.
